# Generated by Django 4.0 on 2022-03-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=50, verbose_name='Тема вопроса')),
                ('quest_text', models.TextField(verbose_name='Текст вопроса')),
                ('quest_date', models.DateTimeField(verbose_name='Тема вопроса')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=50, verbose_name='имя коментатора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст коментатора')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quest')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
